version: "4.12.0"
services:
  mysql:
  image: mattrayner/lamp:latest
  environment:
    MYSQL_ROOT_PASSWORD: Phqc3Vq4KmAS
    MYSQL_DATABASE: zane
    MYSQL_USER: admin
    MYSQL_PASSWORD: Phqc3Vq4KmAS
  ports:
    - "3306:3306"

php:
  image: mattrayner/lamp:latest
  container_name: Lamp
  depends_on:
    - db
  volumes:
    - ./:/var/www/html/
  ports:
    - "80:80"
  stdin_open: true
  tty: true

phpmyadmin:
  image: mattrayner/lamp:latest
  depends_on:
    - db
  external_links:
    - db:mysql
  ports:
    - "80:80"
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: Phqc3Vq4KmAS
    MYSQL_ROOT_PASSWORD: Phqc3Vq4KmAS
    PMA_HOST: db